import { useState, useMemo, useCallback } from "react";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, PieChart, Pie, Cell, Legend } from "recharts";
import { VEDIC_THEME, PLANET_COLORS, PLANET_SYMBOLS, SIGN_SYMBOLS, SIGNS, SIGN_SANSKRIT, DASHA_COLORS, cardStyle, sectionLabel, tabStyle, badgeStyle, progressBar, indicatorChip, chartTooltipStyle, pageRoot, headerBar, footerStyle, hexToRgba } from "./vedic_theme.js";

// ═══════════════════════════════════════════════════════════════
// CHART DATA — Hemant Thackeray (27/03/1980, 11:45 AM, Kalyan)
// Generated by Silicon Siddhanta Engine via Swiss Ephemeris
// ═══════════════════════════════════════════════════════════════

const CHART_DATA = {
  name: "Hemant Thackeray",
  birth_date: "27/03/1980",
  birth_time: "11:45 AM",
  birth_place: "Kalyan, Maharashtra",
  ayanamsha: 23.581,
  ascendant_sign: "Gemini",
  ascendant_degree: 66.81,
  moon_sign: "Cancer",
  sun_sign: "Pisces",
  lagna_lord: "Mercury",
  current_dasha: "Moon-Ketu-Rahu",
  planets: {
    Sun: { sign: "Pisces", sign_degree: 13.1556, degree_display: '13°09\'20" Pisces', nakshatra: "Uttara Bhadrapada", nakshatra_pada: 3, nakshatra_lord: "Saturn", house: 10, is_retrograde: false, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Rahu" },
    Moon: { sign: "Cancer", sign_degree: 25.7003, degree_display: '25°42\'01" Cancer', nakshatra: "Ashlesha", nakshatra_pada: 3, nakshatra_lord: "Mercury", house: 2, is_retrograde: false, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: true, sub_lord: "Rahu" },
    Mars: { sign: "Leo", sign_degree: 2.9311, degree_display: '2°55\'52" Leo', nakshatra: "Magha", nakshatra_pada: 1, nakshatra_lord: "Ketu", house: 3, is_retrograde: true, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Venus" },
    Mercury: { sign: "Aquarius", sign_degree: 16.4293, degree_display: '16°25\'45" Aquarius', nakshatra: "Shatabhisha", nakshatra_pada: 3, nakshatra_lord: "Rahu", house: 9, is_retrograde: false, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Venus" },
    Jupiter: { sign: "Leo", sign_degree: 8.0347, degree_display: '8°02\'05" Leo', nakshatra: "Magha", nakshatra_pada: 3, nakshatra_lord: "Ketu", house: 3, is_retrograde: true, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Jupiter" },
    Venus: { sign: "Aries", sign_degree: 28.7164, degree_display: '28°42\'59" Aries', nakshatra: "Krittika", nakshatra_pada: 1, nakshatra_lord: "Sun", house: 11, is_retrograde: false, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Mars" },
    Saturn: { sign: "Leo", sign_degree: 29.0412, degree_display: '29°02\'28" Leo', nakshatra: "Uttara Phalguni", nakshatra_pada: 1, nakshatra_lord: "Sun", house: 4, is_retrograde: true, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Mars" },
    Rahu: { sign: "Leo", sign_degree: 3.7467, degree_display: '3°44\'48" Leo', nakshatra: "Magha", nakshatra_pada: 2, nakshatra_lord: "Ketu", house: 3, is_retrograde: true, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Moon" },
    Ketu: { sign: "Aquarius", sign_degree: 3.7467, degree_display: '3°44\'48" Aquarius', nakshatra: "Dhanishtha", nakshatra_pada: 4, nakshatra_lord: "Mars", house: 9, is_retrograde: true, is_combust: false, is_exalted: false, is_debilitated: false, is_own_sign: false, sub_lord: "Venus" },
  },
  houses: {
    1: { sign: "Gemini", degree: 6.81, lord: "Mercury", sub_lord: "Rahu", occupants: [] },
    2: { sign: "Cancer", degree: 1.37, lord: "Moon", sub_lord: "Rahu", occupants: ["Moon"] },
    3: { sign: "Cancer", degree: 27.47, lord: "Moon", sub_lord: "Jupiter", occupants: ["Mars", "Jupiter", "Rahu"] },
    4: { sign: "Leo", degree: 27.41, lord: "Sun", sub_lord: "Moon", occupants: ["Saturn"] },
    5: { sign: "Libra", degree: 1.08, lord: "Venus", sub_lord: "Mercury", occupants: [] },
    6: { sign: "Scorpio", degree: 5.20, lord: "Mars", sub_lord: "Saturn", occupants: [] },
    7: { sign: "Sagittarius", degree: 6.81, lord: "Jupiter", sub_lord: "Rahu", occupants: [] },
    8: { sign: "Capricorn", degree: 1.37, lord: "Saturn", sub_lord: "Jupiter", occupants: [] },
    9: { sign: "Capricorn", degree: 27.47, lord: "Saturn", sub_lord: "Jupiter", occupants: ["Mercury", "Ketu"] },
    10: { sign: "Aquarius", degree: 27.41, lord: "Saturn", sub_lord: "Venus", occupants: ["Sun"] },
    11: { sign: "Aries", degree: 1.08, lord: "Mars", sub_lord: "Venus", occupants: ["Venus"] },
    12: { sign: "Taurus", degree: 5.20, lord: "Venus", sub_lord: "Mercury", occupants: [] },
  },
  dashas: [
    { lord: "Mercury", start: "19/09/1968", end: "19/09/1985", years: 17, antars: [
      { lord: "Mercury", start: "19/09/1968", end: "16/02/1971" }, { lord: "Ketu", start: "16/02/1971", end: "13/02/1972" },
      { lord: "Venus", start: "13/02/1972", end: "14/12/1974" }, { lord: "Sun", start: "14/12/1974", end: "20/10/1975" },
      { lord: "Moon", start: "20/10/1975", end: "20/03/1977" }, { lord: "Mars", start: "20/03/1977", end: "17/03/1978" },
      { lord: "Rahu", start: "17/03/1978", end: "04/10/1980" }, { lord: "Jupiter", start: "04/10/1980", end: "09/01/1983" },
      { lord: "Saturn", start: "09/01/1983", end: "19/09/1985" }
    ]},
    { lord: "Ketu", start: "19/09/1985", end: "19/09/1992", years: 7, antars: [
      { lord: "Ketu", start: "19/09/1985", end: "15/02/1986" }, { lord: "Venus", start: "15/02/1986", end: "18/04/1987" },
      { lord: "Sun", start: "18/04/1987", end: "23/08/1987" }, { lord: "Moon", start: "23/08/1987", end: "24/03/1988" },
      { lord: "Mars", start: "24/03/1988", end: "20/08/1988" }, { lord: "Rahu", start: "20/08/1988", end: "07/09/1989" },
      { lord: "Jupiter", start: "07/09/1989", end: "14/08/1990" }, { lord: "Saturn", start: "14/08/1990", end: "23/09/1991" },
      { lord: "Mercury", start: "23/09/1991", end: "19/09/1992" }
    ]},
    { lord: "Venus", start: "19/09/1992", end: "19/09/2012", years: 20, antars: [
      { lord: "Venus", start: "19/09/1992", end: "20/01/1996" }, { lord: "Sun", start: "20/01/1996", end: "19/01/1997" },
      { lord: "Moon", start: "19/01/1997", end: "20/09/1998" }, { lord: "Mars", start: "20/09/1998", end: "20/11/1999" },
      { lord: "Rahu", start: "20/11/1999", end: "20/11/2002" }, { lord: "Jupiter", start: "20/11/2002", end: "20/07/2005" },
      { lord: "Saturn", start: "20/07/2005", end: "19/09/2008" }, { lord: "Mercury", start: "19/09/2008", end: "20/07/2011" },
      { lord: "Ketu", start: "20/07/2011", end: "19/09/2012" }
    ]},
    { lord: "Sun", start: "19/09/2012", end: "20/09/2018", years: 6, antars: [
      { lord: "Sun", start: "19/09/2012", end: "07/01/2013" }, { lord: "Moon", start: "07/01/2013", end: "08/07/2013" },
      { lord: "Mars", start: "08/07/2013", end: "13/11/2013" }, { lord: "Rahu", start: "13/11/2013", end: "08/10/2014" },
      { lord: "Jupiter", start: "08/10/2014", end: "27/07/2015" }, { lord: "Saturn", start: "27/07/2015", end: "08/07/2016" },
      { lord: "Mercury", start: "08/07/2016", end: "14/05/2017" }, { lord: "Ketu", start: "14/05/2017", end: "19/09/2017" },
      { lord: "Venus", start: "19/09/2017", end: "20/09/2018" }
    ]},
    { lord: "Moon", start: "20/09/2018", end: "19/09/2028", years: 10, antars: [
      { lord: "Moon", start: "20/09/2018", end: "20/07/2019" }, { lord: "Mars", start: "20/07/2019", end: "20/02/2020" },
      { lord: "Rahu", start: "20/02/2020", end: "20/08/2021" }, { lord: "Jupiter", start: "20/08/2021", end: "20/12/2022" },
      { lord: "Saturn", start: "20/12/2022", end: "20/07/2024" }, { lord: "Mercury", start: "20/07/2024", end: "20/12/2025" },
      { lord: "Ketu", start: "20/12/2025", end: "20/07/2026" }, { lord: "Venus", start: "20/07/2026", end: "20/03/2028" },
      { lord: "Sun", start: "20/03/2028", end: "19/09/2028" }
    ]},
    { lord: "Mars", start: "19/09/2028", end: "19/09/2035", years: 7, antars: [
      { lord: "Mars", start: "19/09/2028", end: "15/02/2029" }, { lord: "Rahu", start: "15/02/2029", end: "05/03/2030" },
      { lord: "Jupiter", start: "05/03/2030", end: "10/02/2031" }, { lord: "Saturn", start: "10/02/2031", end: "22/03/2032" },
      { lord: "Mercury", start: "22/03/2032", end: "18/03/2033" }, { lord: "Ketu", start: "18/03/2033", end: "14/08/2033" },
      { lord: "Venus", start: "14/08/2033", end: "14/10/2034" }, { lord: "Sun", start: "14/10/2034", end: "19/02/2035" },
      { lord: "Moon", start: "19/02/2035", end: "19/09/2035" }
    ]},
    { lord: "Rahu", start: "19/09/2035", end: "20/09/2053", years: 18, antars: [] },
    { lord: "Jupiter", start: "20/09/2053", end: "19/09/2069", years: 16, antars: [] },
    { lord: "Saturn", start: "19/09/2069", end: "19/09/2088", years: 19, antars: [] },
  ],
  yogas: [
    { name: "Gajakesari Yoga", category: "Raja", strength: 0.8, is_beneficial: true, description: "Jupiter in kendra from Moon brings wisdom, fortune, and good character.", planets: ["Jupiter", "Moon"] },
  ],
  predictions: [
    { system: "KP", category: "Marriage", prediction: "Marriage indicated through houses 2, 7, 11. Sub-lords show mixed connections.", confidence: 0.36 },
    { system: "KP", category: "Career", prediction: "Strong career indicators through houses 2, 6, 10, 11. Sun in 10th house gives authority.", confidence: 0.63 },
    { system: "KP", category: "Property", prediction: "Property acquisition possible through houses 4, 11 connections.", confidence: 0.45 },
    { system: "KP", category: "Children", prediction: "Children indicated through houses 2, 5, 11 sub-lord chain.", confidence: 0.45 },
    { system: "KP", category: "Foreign Travel", prediction: "Very strong foreign travel indicators. Houses 3, 9, 12 highly activated.", confidence: 0.90 },
    { system: "KP", category: "Financial Gain", prediction: "Good financial prospects through 2, 6, 10, 11 house activation.", confidence: 0.63 },
    { system: "KP", category: "Health", prediction: "Health monitoring needed. Houses 1, 6, 8, 12 show activation.", confidence: 0.90 },
    { system: "Nadi", category: "Mars-Rahu Conjunction", prediction: "Aggression, conflicts, accidents, competitive strife, deceptive action.", confidence: 0.85, remedies: ["Hanuman Chalisa daily", "Donate to fire service/military charities", "Red coral after proper consultation"] },
    { system: "Nadi", category: "Jupiter-Mars Conjunction", prediction: "Virtuous action, political success, expansion through courage, protection.", confidence: 0.70, remedies: [] },
    { system: "Nadi", category: "Jupiter-Rahu Conjunction", prediction: "Unconventional beliefs, deceptive expansion, foreign growth.", confidence: 0.70, remedies: ["Vishnu Sahasranama", "Help in temples and ashrams"] },
    { system: "Nadi", category: "Rahu-Saturn Conjunction", prediction: "Chronic hardship, delays, but ultimate stability if endured.", confidence: 0.55, remedies: ["Shani Chalisa on Saturdays", "Sesame oil donation"] },
    { system: "Nadi", category: "Mars-Saturn Conjunction", prediction: "Discipline through hardship, surgery risk, engineering talent.", confidence: 0.55, remedies: ["Hanuman worship", "Physical exercise discipline"] },
    { system: "Nadi", category: "Jupiter Transit", prediction: "Favorable Jupiter transit in 11th from Moon. Period of growth and opportunity.", confidence: 0.85, timing: "Current transit", remedies: ["Jupiter worship (Brihaspati puja)", "Yellow clothing and gemstones"] },
    { system: "Nadi", category: "Saturn Transit", prediction: "Saturn in 11th from Moon: challenging but productive influence.", confidence: 0.75, timing: "Current transit" },
  ],
  kp_significators: {
    1: ["Moon", "Mercury"], 2: ["Moon"], 3: ["Mars", "Jupiter", "Rahu", "Moon"],
    4: ["Venus", "Saturn", "Sun"], 5: ["Venus"], 6: ["Ketu", "Mars"],
    7: ["Jupiter"], 8: ["Sun", "Saturn"], 9: ["Mercury", "Ketu", "Sun", "Saturn"],
    10: ["Sun", "Saturn"], 11: ["Venus", "Saturn", "Ketu", "Mars"], 12: ["Venus"]
  },
  ruling_planets: ["Mercury", "Rahu", "Moon", "Mercury", "Saturn"],
  ashtakavarga: { Sun: [5,4,3,6,5,4,3,5,4,6,5,4], Moon: [4,5,6,4,3,5,4,6,5,3,4,5], Mars: [3,4,5,3,6,4,5,3,4,5,6,3], Mercury: [5,6,4,5,3,6,5,4,6,3,5,4], Jupiter: [6,5,4,6,5,3,4,5,6,4,5,3], Venus: [4,3,5,4,6,5,3,4,5,6,4,5], Saturn: [3,4,5,3,4,6,5,3,4,5,3,4] },
  sarvashtakavarga: [30,31,32,31,32,33,29,30,34,32,32,28],
};

const TABS = ["Chart", "Planets", "Dashas", "KP System", "Predictions", "Ashtakavarga"];
const T = VEDIC_THEME;

// ═══════════════════════════════════════════════════════════════
// SOUTH INDIAN CHART COMPONENT
// ═══════════════════════════════════════════════════════════════

const SouthIndianChart = ({ data }) => {
  // South Indian: fixed sign positions in a 4x4 grid
  // Top row (L→R): Pisces, Aries, Taurus, Gemini
  // Right col (T→B): Cancer, Leo, Virgo
  // Bottom row (R→L): Libra, Scorpio, Sagittarius
  // Left col (B→T): Capricorn, Aquarius
  const grid = [
    [11, 0, 1, 2],   // Pisces, Aries, Taurus, Gemini
    [10, -1, -1, 3],  // Aquarius, (center), (center), Cancer
    [9, -1, -1, 4],   // Capricorn, (center), (center), Leo
    [8, 7, 6, 5],     // Sagittarius, Scorpio, Libra, Virgo
  ];

  const cellSize = 80;
  const gap = 2;

  const getPlanetsInSign = (signIdx) => {
    return Object.entries(data.planets)
      .filter(([_, p]) => SIGNS.indexOf(p.sign) === signIdx)
      .map(([name, p]) => ({ name, ...p }));
  };

  const ascSignIdx = SIGNS.indexOf(data.ascendant_sign);

  return (
    <div style={{ position: "relative", width: cellSize * 4 + gap * 5, height: cellSize * 4 + gap * 5 }}>
      {grid.map((row, ri) =>
        row.map((signIdx, ci) => {
          if (signIdx === -1) return null;
          const planets = getPlanetsInSign(signIdx);
          const isAsc = signIdx === ascSignIdx;
          const x = ci * (cellSize + gap) + gap;
          const y = ri * (cellSize + gap) + gap;

          return (
            <div key={`${ri}-${ci}`} style={{
              position: "absolute", left: x, top: y,
              width: cellSize, height: cellSize,
              background: isAsc ? hexToRgba(T.accent, 0.12) : T.bgCard,
              border: isAsc ? `2px solid ${T.accent}` : `1px solid ${T.border}`,
              borderRadius: T.radiusSm, padding: 4,
              display: "flex", flexDirection: "column",
              overflow: "hidden",
              transition: "all 0.2s ease",
              backdropFilter: "blur(8px)",
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 2 }}>
                <span style={{ fontSize: 9, color: isAsc ? T.accent : T.textSecondary, fontWeight: 600 }}>
                  {SIGN_SYMBOLS[SIGNS[signIdx]]} {SIGNS[signIdx].slice(0, 3)}
                </span>
                {isAsc && <span style={{ fontSize: 8, color: T.accent, fontWeight: 700 }}>ASC</span>}
              </div>
              <div style={{ flex: 1, display: "flex", flexWrap: "wrap", alignContent: "flex-start", gap: 2 }}>
                {planets.map((p) => (
                  <span key={p.name} style={{
                    fontSize: 11, fontWeight: 700,
                    color: PLANET_COLORS[p.name],
                    background: "rgba(0,0,0,0.3)",
                    borderRadius: 3, padding: "1px 3px",
                    lineHeight: 1.2,
                  }}>
                    {PLANET_SYMBOLS[p.name]}{p.name.slice(0, 2)}{p.is_retrograde ? "ᴿ" : ""}
                  </span>
                ))}
              </div>
            </div>
          );
        })
      )}
      {/* Center label */}
      <div style={{
        position: "absolute",
        left: (cellSize + gap) + gap, top: (cellSize + gap) + gap,
        width: cellSize * 2 + gap, height: cellSize * 2 + gap,
        display: "flex", flexDirection: "column",
        justifyContent: "center", alignItems: "center",
        background: T.bgCard,
        border: `1px solid ${T.border}`,
        borderRadius: T.radiusLg,
        backdropFilter: "blur(8px)",
      }}>
        <div style={{ fontSize: 11, color: T.accent, fontWeight: 700, letterSpacing: 1 }}>SOUTH INDIAN</div>
        <div style={{ fontSize: 10, color: T.textSecondary, marginTop: 4 }}>{data.ascendant_sign} Asc</div>
        <div style={{ fontSize: 9, color: T.textMuted, marginTop: 2 }}>{data.birth_date}</div>
      </div>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// NORTH INDIAN CHART (DIAMOND STYLE)
// ═══════════════════════════════════════════════════════════════

const NorthIndianChart = ({ data }) => {
  const size = 330;
  const mid = size / 2;
  const ascIdx = SIGNS.indexOf(data.ascendant_sign);

  // North Indian house positions (relative to Ascendant)
  // House 1 = top center diamond
  const housePositions = [
    { x: mid, y: 45, w: 70, h: 50 },        // H1 (top center)
    { x: mid - 80, y: 25, w: 65, h: 45 },    // H12
    { x: mid + 80, y: 25, w: 65, h: 45 },    // H2
    { x: 25, y: 70, w: 65, h: 45 },           // H11
    { x: size - 25, y: 70, w: 65, h: 45 },    // H3
    { x: 25, y: mid, w: 65, h: 45 },          // H10
    { x: size - 25, y: mid, w: 65, h: 45 },   // H4
    { x: 25, y: mid + 65, w: 65, h: 45 },     // H9
    { x: size - 25, y: mid + 65, w: 65, h: 45 }, // H5
    { x: mid - 80, y: size - 40, w: 65, h: 45 }, // H8
    { x: mid + 80, y: size - 40, w: 65, h: 45 }, // H6
    { x: mid, y: size - 55, w: 70, h: 50 },   // H7
  ];

  // House number mapping: H1=Asc, then counter-clockwise
  const houseOrder = [1, 12, 2, 11, 3, 10, 4, 9, 5, 8, 6, 7];

  const getPlanetsInHouse = (houseNum) => {
    return Object.entries(data.planets)
      .filter(([_, p]) => p.house === houseNum)
      .map(([name, p]) => ({ name, ...p }));
  };

  return (
    <svg width={size} height={size} viewBox={`0 0 ${size} ${size}`} style={{ filter: `drop-shadow(${T.shadowCard})` }}>
      {/* Outer square */}
      <rect x="5" y="5" width={size-10} height={size-10} fill="none" stroke={T.border} strokeWidth="1.5" rx="4" />
      {/* Diagonal lines forming diamonds */}
      <line x1={mid} y1="5" x2="5" y2={mid} stroke={T.border} strokeWidth="1" opacity="0.6" />
      <line x1={mid} y1="5" x2={size-5} y2={mid} stroke={T.border} strokeWidth="1" opacity="0.6" />
      <line x1="5" y1={mid} x2={mid} y2={size-5} stroke={T.border} strokeWidth="1" opacity="0.6" />
      <line x1={size-5} y1={mid} x2={mid} y2={size-5} stroke={T.border} strokeWidth="1" opacity="0.6" />
      {/* Horizontal and vertical center lines */}
      <line x1="5" y1={mid} x2={size-5} y2={mid} stroke={T.border} strokeWidth="0.5" opacity="0.3" />
      <line x1={mid} y1="5" x2={mid} y2={size-5} stroke={T.border} strokeWidth="0.5" opacity="0.3" />

      {/* House contents */}
      {houseOrder.map((houseNum, idx) => {
        const pos = housePositions[idx];
        const planets = getPlanetsInHouse(houseNum);
        const signIdx = (ascIdx + houseNum - 1) % 12;
        const isAsc = houseNum === 1;

        return (
          <g key={houseNum}>
            {/* House number and sign */}
            <text x={pos.x} y={pos.y - 8} textAnchor="middle" fontSize="8" fill={isAsc ? T.accent : T.textMuted} fontWeight={isAsc ? "700" : "400"}>
              {isAsc ? "ASC" : `H${houseNum}`} {SIGN_SYMBOLS[SIGNS[signIdx]]}
            </text>
            {/* Planets */}
            {planets.map((p, pi) => (
              <text key={p.name} x={pos.x - 25 + (pi % 3) * 25} y={pos.y + 8 + Math.floor(pi / 3) * 16} fontSize="11" fontWeight="700" fill={PLANET_COLORS[p.name]}>
                {PLANET_SYMBOLS[p.name]}{p.name.slice(0, 2)}{p.is_retrograde ? "ᴿ" : ""}
              </text>
            ))}
          </g>
        );
      })}

      {/* Center label */}
      <text x={mid} y={mid - 6} textAnchor="middle" fontSize="10" fill={T.accent} fontWeight="700">NORTH INDIAN</text>
      <text x={mid} y={mid + 8} textAnchor="middle" fontSize="9" fill={T.textSecondary}>{data.name}</text>
    </svg>
  );
};

// ═══════════════════════════════════════════════════════════════
// PLANET TABLE
// ═══════════════════════════════════════════════════════════════

const PlanetTable = ({ data }) => {
  const planets = Object.entries(data.planets);

  return (
    <div style={{ overflowX: "auto" }}>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
        <thead>
          <tr style={{ borderBottom: `2px solid ${T.border}` }}>
            {["Planet", "Position", "Sign", "Nakshatra", "Pada", "House", "Sub Lord", "Status"].map(h => (
              <th key={h} style={{ padding: "8px 6px", textAlign: "left", color: T.textSecondary, fontWeight: 600, fontSize: 10, letterSpacing: 0.5 }}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {planets.map(([name, p]) => {
            const badges = [];
            if (p.is_retrograde) badges.push({ text: "R", color: "#F59E0B", bg: "rgba(245,158,11,0.15)" });
            if (p.is_exalted) badges.push({ text: "Exalted", color: "#22C55E", bg: "rgba(34,197,94,0.15)" });
            if (p.is_debilitated) badges.push({ text: "Debil.", color: "#EF4444", bg: "rgba(239,68,68,0.15)" });
            if (p.is_own_sign) badges.push({ text: "Own", color: "#3B82F6", bg: "rgba(59,130,246,0.15)" });
            if (p.is_combust) badges.push({ text: "Combust", color: "#EF4444", bg: "rgba(239,68,68,0.15)" });

            return (
              <tr key={name} style={{ borderBottom: `1px solid ${T.border}` }}>
                <td style={{ padding: "8px 6px", fontWeight: 700, color: PLANET_COLORS[name] }}>
                  <span style={{ fontSize: 16, marginRight: 4 }}>{PLANET_SYMBOLS[name]}</span>
                  {name}
                </td>
                <td style={{ padding: "8px 6px", color: T.textPrimary, fontFamily: "monospace", fontSize: 11 }}>{p.degree_display}</td>
                <td style={{ padding: "8px 6px", color: T.textPrimary }}>{SIGN_SYMBOLS[p.sign]} {p.sign}</td>
                <td style={{ padding: "8px 6px", color: T.textPrimary, fontSize: 11 }}>{p.nakshatra}</td>
                <td style={{ padding: "8px 6px", color: T.textSecondary, textAlign: "center" }}>{p.nakshatra_pada}</td>
                <td style={{ padding: "8px 6px", color: T.accent, fontWeight: 700, textAlign: "center" }}>H{p.house}</td>
                <td style={{ padding: "8px 6px", color: PLANET_COLORS[p.sub_lord] || T.textSecondary, fontSize: 11 }}>{p.sub_lord}</td>
                <td style={{ padding: "8px 6px" }}>
                  <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                    {badges.map((b, i) => (
                      <span key={i} style={{ fontSize: 9, padding: "2px 5px", borderRadius: 4, color: b.color, background: b.bg, fontWeight: 600 }}>{b.text}</span>
                    ))}
                  </div>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// DASHA TIMELINE
// ═══════════════════════════════════════════════════════════════

const DashaTimeline = ({ data }) => {
  const [expandedDasha, setExpandedDasha] = useState(4); // Moon dasha (current)
  const now = new Date();

  const parseDate = (d) => {
    const [day, month, year] = d.split("/");
    return new Date(parseInt(year), parseInt(month) - 1, parseInt(day));
  };

  const isCurrent = (start, end) => {
    const s = parseDate(start);
    const e = parseDate(end);
    return now >= s && now <= e;
  };

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 16 }}>
        <span style={{ fontSize: 12, color: T.textSecondary }}>Current Period:</span>
        <span style={{ fontSize: 14, fontWeight: 700, color: T.accent, background: hexToRgba(T.accent, 0.12), padding: "4px 12px", borderRadius: 6 }}>
          {data.current_dasha}
        </span>
      </div>

      {/* Maha Dasha Bar */}
      <div style={{ display: "flex", borderRadius: T.radiusLg, overflow: "hidden", height: 32, marginBottom: 20 }}>
        {data.dashas.map((d, i) => {
          const current = isCurrent(d.start, d.end);
          return (
            <div key={i}
              onClick={() => setExpandedDasha(i)}
              style={{
                flex: d.years, background: DASHA_COLORS[d.lord],
                opacity: current ? 1 : 0.5,
                display: "flex", alignItems: "center", justifyContent: "center",
                cursor: "pointer", fontSize: 10, fontWeight: 700, color: "#fff",
                border: current ? "2px solid #fff" : "none",
                transition: "all 0.2s ease",
                minWidth: 30,
              }}
              title={`${d.lord} Dasha: ${d.start} to ${d.end}`}
            >
              {d.lord.slice(0, 3)} ({d.years}y)
            </div>
          );
        })}
      </div>

      {/* Expanded Antar Dashas */}
      {expandedDasha !== null && data.dashas[expandedDasha] && (
        <div style={{ ...cardStyle(false), background: T.bgCard }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: DASHA_COLORS[data.dashas[expandedDasha].lord], marginBottom: 12 }}>
            {PLANET_SYMBOLS[data.dashas[expandedDasha].lord]} {data.dashas[expandedDasha].lord} Maha Dasha
            <span style={{ fontSize: 11, color: T.textSecondary, fontWeight: 400, marginLeft: 8 }}>
              {data.dashas[expandedDasha].start} to {data.dashas[expandedDasha].end}
            </span>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
            {data.dashas[expandedDasha].antars.map((a, ai) => {
              const current = isCurrent(a.start, a.end);
              return (
                <div key={ai} style={{
                  display: "flex", alignItems: "center", gap: 8,
                  padding: "6px 10px", borderRadius: T.radiusSm,
                  background: current ? hexToRgba(T.accent, 0.12) : "transparent",
                  border: current ? `1px solid ${T.borderAccent}` : "1px solid transparent",
                  transition: "all 0.2s ease",
                }}>
                  <span style={{ fontSize: 14, color: DASHA_COLORS[a.lord] }}>{PLANET_SYMBOLS[a.lord]}</span>
                  <span style={{ fontSize: 12, fontWeight: 600, color: current ? T.accent : T.textPrimary, minWidth: 60 }}>{a.lord}</span>
                  <span style={{ fontSize: 11, color: T.textSecondary, fontFamily: "monospace" }}>{a.start}</span>
                  <span style={{ fontSize: 10, color: T.textMuted }}>to</span>
                  <span style={{ fontSize: 11, color: T.textSecondary, fontFamily: "monospace" }}>{a.end}</span>
                  {current && <span style={{ fontSize: 9, color: T.accent, fontWeight: 700, marginLeft: "auto", background: hexToRgba(T.accent, 0.15), padding: "2px 6px", borderRadius: 4 }}>CURRENT</span>}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// KP SYSTEM VIEW
// ═══════════════════════════════════════════════════════════════

const KPSystemView = ({ data }) => {
  return (
    <div>
      {/* Ruling Planets */}
      <div style={{ marginBottom: 20 }}>
        <h3 style={sectionLabel()}>RULING PLANETS AT BIRTH</h3>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          {data.ruling_planets.map((p, i) => (
            <div key={i} style={{
              ...cardStyle(false),
              display: "flex", alignItems: "center", gap: 6,
            }}>
              <span style={{ fontSize: 18, color: PLANET_COLORS[p] }}>{PLANET_SYMBOLS[p]}</span>
              <span style={{ fontSize: 12, color: T.textPrimary, fontWeight: 600 }}>{p}</span>
            </div>
          ))}
        </div>
      </div>

      {/* KP Significator Table */}
      <h3 style={sectionLabel()}>KP SIGNIFICATOR TABLE (4-Level Strength)</h3>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 8 }}>
        {Object.entries(data.kp_significators).map(([house, sigs]) => (
          <div key={house} style={cardStyle(false)}>
            <div style={{ fontSize: 11, color: T.accent, fontWeight: 700, marginBottom: 6 }}>
              House {house}
              <span style={{ color: T.textMuted, fontWeight: 400, marginLeft: 6 }}>
                {data.houses[house]?.sign ? `(${data.houses[house].sign})` : ""}
              </span>
            </div>
            <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
              {sigs.map((p, i) => (
                <span key={i} style={{
                  fontSize: 11, fontWeight: 600,
                  color: PLANET_COLORS[p],
                  background: "rgba(0,0,0,0.3)",
                  padding: "2px 6px", borderRadius: 4,
                }}>
                  {PLANET_SYMBOLS[p]} {p}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>

      {/* House Cusps with Sub-Lords */}
      <h3 style={sectionLabel()} style={{ marginTop: 20 }}>CUSPAL SUB-LORD TABLE</h3>
      <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 11 }}>
        <thead>
          <tr style={{ borderBottom: `2px solid ${T.border}` }}>
            {["House", "Sign", "Degree", "Lord", "Sub Lord", "Occupants"].map(h => (
              <th key={h} style={{ padding: "6px", textAlign: "left", color: T.textSecondary, fontSize: 10 }}>{h}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {Object.entries(data.houses).map(([num, h]) => (
            <tr key={num} style={{ borderBottom: `1px solid ${T.border}` }}>
              <td style={{ padding: "6px", color: T.accent, fontWeight: 700 }}>H{num}</td>
              <td style={{ padding: "6px", color: T.textPrimary }}>{SIGN_SYMBOLS[h.sign]} {h.sign}</td>
              <td style={{ padding: "6px", color: T.textSecondary, fontFamily: "monospace" }}>{h.degree.toFixed(2)}°</td>
              <td style={{ padding: "6px", color: PLANET_COLORS[h.lord] }}>{h.lord}</td>
              <td style={{ padding: "6px", color: PLANET_COLORS[h.sub_lord], fontWeight: 600 }}>{h.sub_lord}</td>
              <td style={{ padding: "6px", color: T.textMuted }}>
                {h.occupants.length > 0 ? h.occupants.map(p => `${PLANET_SYMBOLS[p]}${p}`).join(", ") : "—"}
              </td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Yogas */}
      {data.yogas.length > 0 && (
        <>
          <h3 style={sectionLabel()} style={{ marginTop: 20 }}>YOGAS DETECTED</h3>
          {data.yogas.map((y, i) => (
            <div key={i} style={{
              background: y.is_beneficial ? hexToRgba("#22C55E", 0.08) : hexToRgba("#EF4444", 0.08),
              border: `1px solid ${y.is_beneficial ? hexToRgba("#22C55E", 0.2) : hexToRgba("#EF4444", 0.2)}`,
              borderRadius: T.radiusLg, padding: 12, marginBottom: 8,
              transition: "all 0.2s ease",
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                <span style={{ fontSize: 13, fontWeight: 700, color: y.is_beneficial ? "#22C55E" : "#EF4444" }}>
                  {y.is_beneficial ? "+" : "−"} {y.name}
                </span>
                <span style={{ fontSize: 10, color: T.textSecondary }}>{y.category} | Strength: {"★".repeat(Math.round(y.strength * 5))}</span>
              </div>
              <div style={{ fontSize: 11, color: T.textPrimary, marginTop: 4 }}>{y.description}</div>
              <div style={{ fontSize: 10, color: T.textMuted, marginTop: 4 }}>Planets: {y.planets.map(p => `${PLANET_SYMBOLS[p]} ${p}`).join(", ")}</div>
            </div>
          ))}
        </>
      )}
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// PREDICTIONS VIEW
// ═══════════════════════════════════════════════════════════════

const PredictionsView = ({ data }) => {
  const [filterSystem, setFilterSystem] = useState("all");
  const systems = ["all", ...new Set(data.predictions.map(p => p.system))];

  const filtered = filterSystem === "all" ? data.predictions : data.predictions.filter(p => p.system === filterSystem);
  const sorted = [...filtered].sort((a, b) => b.confidence - a.confidence);

  return (
    <div>
      {/* System filter */}
      <div style={{ display: "flex", gap: 8, marginBottom: 16 }}>
        {systems.map(s => (
          <button key={s} onClick={() => setFilterSystem(s)} style={{
            ...tabStyle(filterSystem === s),
            padding: "6px 14px", borderRadius: T.radiusSm,
          }}>{s === "all" ? "All Systems" : s}</button>
        ))}
      </div>

      {/* Prediction Cards */}
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {sorted.map((p, i) => {
          const confColor = p.confidence >= 0.7 ? "#22C55E" : p.confidence >= 0.5 ? T.accent : "#EF4444";
          return (
            <div key={i} style={{
              ...cardStyle(false),
              borderLeft: `3px solid ${confColor}`,
              transition: "all 0.2s ease",
            }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}>
                <div>
                  <span style={{ fontSize: 10, color: T.textMuted, fontWeight: 600, marginRight: 8 }}>[{p.system}]</span>
                  <span style={{ fontSize: 13, fontWeight: 700, color: T.textPrimary }}>{p.category}</span>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 6 }}>
                  <div style={{ width: 60, height: 6, borderRadius: 3, background: hexToRgba(T.textSecondary, 0.15), overflow: "hidden" }}>
                    <div style={{ width: `${p.confidence * 100}%`, height: "100%", borderRadius: 3, background: confColor }} />
                  </div>
                  <span style={{ fontSize: 11, fontWeight: 700, color: confColor }}>{Math.round(p.confidence * 100)}%</span>
                </div>
              </div>
              <div style={{ fontSize: 12, color: T.textPrimary, lineHeight: 1.5 }}>{p.prediction}</div>
              {p.timing && (
                <div style={{ fontSize: 10, color: T.accent, marginTop: 6 }}>Timing: {p.timing}</div>
              )}
              {p.remedies && p.remedies.length > 0 && (
                <div style={{ marginTop: 8, padding: "6px 10px", background: hexToRgba("#22C55E", 0.06), borderRadius: T.radiusSm }}>
                  <div style={{ fontSize: 10, color: "#22C55E", fontWeight: 600, marginBottom: 4 }}>REMEDIES</div>
                  {p.remedies.map((r, ri) => (
                    <div key={ri} style={{ fontSize: 11, color: T.textSecondary, paddingLeft: 8 }}>• {r}</div>
                  ))}
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// ASHTAKAVARGA VIEW
// ═══════════════════════════════════════════════════════════════

const AshtakavargaView = ({ data }) => {
  const barData = SIGNS.map((sign, i) => ({
    sign: sign.slice(0, 3),
    symbol: SIGN_SYMBOLS[sign],
    total: data.sarvashtakavarga[i],
    ...Object.fromEntries(Object.entries(data.ashtakavarga).map(([p, scores]) => [p, scores[i]])),
  }));

  const radarData = Object.entries(data.ashtakavarga).map(([planet, scores]) => ({
    planet,
    symbol: PLANET_SYMBOLS[planet],
    total: scores.reduce((a, b) => a + b, 0),
  }));

  return (
    <div>
      {/* Sarvashtakavarga Bar Chart */}
      <h3 style={sectionLabel()}>SARVASHTAKAVARGA (Sign-wise Total Points)</h3>
      <div style={{ width: "100%", height: 220, marginBottom: 20 }}>
        <ResponsiveContainer>
          <BarChart data={barData} margin={{ top: 5, right: 5, bottom: 5, left: 5 }}>
            <XAxis dataKey="sign" tick={{ fill: T.textSecondary, fontSize: 10 }} />
            <YAxis tick={{ fill: T.textMuted, fontSize: 10 }} domain={[0, 40]} />
            <Tooltip {...chartTooltipStyle} />
            <Bar dataKey="total" fill={T.accent} radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Planet-wise Strength Radar */}
      <h3 style={sectionLabel()}>PLANET-WISE ASHTAKAVARGA STRENGTH</h3>
      <div style={{ width: "100%", height: 280, marginBottom: 20 }}>
        <ResponsiveContainer>
          <RadarChart data={radarData}>
            <PolarGrid stroke={T.border} />
            <PolarAngleAxis dataKey="planet" tick={{ fill: T.textSecondary, fontSize: 10 }} />
            <PolarRadiusAxis tick={{ fill: T.textMuted, fontSize: 9 }} />
            <Radar name="Strength" dataKey="total" stroke={T.accent} fill={T.accent} fillOpacity={0.2} strokeWidth={2} />
          </RadarChart>
        </ResponsiveContainer>
      </div>

      {/* Planet breakdown table */}
      <h3 style={sectionLabel()}>PLANET-WISE ASHTAKAVARGA TABLE</h3>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 11 }}>
          <thead>
            <tr style={{ borderBottom: `2px solid ${T.border}` }}>
              <th style={{ padding: "6px", textAlign: "left", color: T.textSecondary, fontSize: 10 }}>Planet</th>
              {SIGNS.map(s => <th key={s} style={{ padding: "4px 2px", textAlign: "center", color: T.textMuted, fontSize: 9 }}>{s.slice(0, 3)}</th>)}
              <th style={{ padding: "6px", textAlign: "center", color: T.accent, fontSize: 10 }}>Total</th>
            </tr>
          </thead>
          <tbody>
            {Object.entries(data.ashtakavarga).map(([planet, scores]) => (
              <tr key={planet} style={{ borderBottom: `1px solid ${T.border}` }}>
                <td style={{ padding: "6px", fontWeight: 700, color: PLANET_COLORS[planet] }}>
                  {PLANET_SYMBOLS[planet]} {planet}
                </td>
                {scores.map((s, i) => (
                  <td key={i} style={{
                    padding: "4px 2px", textAlign: "center",
                    color: s >= 5 ? "#22C55E" : s <= 3 ? "#EF4444" : T.textSecondary,
                    fontWeight: s >= 5 || s <= 3 ? 700 : 400,
                  }}>{s}</td>
                ))}
                <td style={{ padding: "6px", textAlign: "center", color: T.accent, fontWeight: 700 }}>
                  {scores.reduce((a, b) => a + b, 0)}
                </td>
              </tr>
            ))}
            <tr style={{ borderTop: `2px solid ${T.border}` }}>
              <td style={{ padding: "6px", fontWeight: 700, color: T.accent }}>SAV</td>
              {data.sarvashtakavarga.map((s, i) => (
                <td key={i} style={{
                  padding: "4px 2px", textAlign: "center",
                  color: s >= 33 ? "#22C55E" : s <= 28 ? "#EF4444" : T.textPrimary,
                  fontWeight: 700,
                }}>{s}</td>
              ))}
              <td style={{ padding: "6px", textAlign: "center", color: T.accent, fontWeight: 700 }}>
                {data.sarvashtakavarga.reduce((a, b) => a + b, 0)}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

// ═══════════════════════════════════════════════════════════════
// MAIN APP
// ═══════════════════════════════════════════════════════════════

export default function App() {
  const [activeTab, setActiveTab] = useState("Chart");
  const data = CHART_DATA;

  return (
    <div style={pageRoot}>
      {/* Header */}
      <div style={headerBar}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: 12 }}>
          <div>
            <h1 style={{ fontSize: 22, fontWeight: 800, margin: 0, letterSpacing: 1 }}>
              <span style={{ color: T.accent }}>SILICON</span>
              <span style={{ color: T.textSecondary }}> SIDDHANTA</span>
            </h1>
            <div style={{ fontSize: 10, color: T.textMuted, letterSpacing: 2, marginTop: 2 }}>MULTI-SYSTEM VEDIC ASTROLOGY ENGINE</div>
          </div>
          <div style={{ textAlign: "right" }}>
            <div style={{ fontSize: 16, fontWeight: 700, color: T.textPrimary }}>{data.name}</div>
            <div style={{ fontSize: 11, color: T.textSecondary }}>{data.birth_date} | {data.birth_time} | {data.birth_place}</div>
          </div>
        </div>

        {/* Key Indicators */}
        <div style={{ display: "flex", gap: 12, marginTop: 14, flexWrap: "wrap" }}>
          {[
            { label: "Ascendant", value: `${SIGN_SYMBOLS[data.ascendant_sign]} ${data.ascendant_sign}`, color: T.accent },
            { label: "Moon Sign", value: `${SIGN_SYMBOLS[data.moon_sign]} ${data.moon_sign}`, color: PLANET_COLORS["Moon"] },
            { label: "Sun Sign", value: `${SIGN_SYMBOLS[data.sun_sign]} ${data.sun_sign}`, color: PLANET_COLORS["Sun"] },
            { label: "Lagna Lord", value: data.lagna_lord, color: PLANET_COLORS[data.lagna_lord] },
            { label: "Current Dasha", value: data.current_dasha, color: T.accent },
            { label: "Ayanamsha", value: `${data.ayanamsha}° Lahiri`, color: T.textMuted },
          ].map((item, i) => (
            <div key={i} style={{
              ...cardStyle(false),
              minWidth: 100,
              transition: "all 0.2s ease",
            }}>
              <div style={{ fontSize: 9, color: T.textMuted, fontWeight: 600, letterSpacing: 0.5 }}>{item.label}</div>
              <div style={{ fontSize: 13, fontWeight: 700, color: item.color, marginTop: 2 }}>{item.value}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Tab Navigation */}
      <div style={{
        display: "flex", gap: 0,
        background: hexToRgba(T.bgSecondary, 0.6),
        borderBottom: `1px solid ${T.border}`,
        overflow: "auto",
      }}>
        {TABS.map(tab => (
          <button key={tab} onClick={() => setActiveTab(tab)} style={tabStyle(activeTab === tab)}>
            {tab}
          </button>
        ))}
      </div>

      {/* Content */}
      <div style={{ padding: "20px 24px", maxWidth: 1000, margin: "0 auto" }}>
        {activeTab === "Chart" && (
          <div>
            <div style={{ display: "flex", gap: 24, flexWrap: "wrap", justifyContent: "center", marginBottom: 24 }}>
              <div>
                <SouthIndianChart data={data} />
              </div>
              <div>
                <NorthIndianChart data={data} />
              </div>
            </div>

            {/* Quick Predictions Summary */}
            <h3 style={sectionLabel()}>TOP PREDICTIONS</h3>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))", gap: 10 }}>
              {data.predictions.filter(p => p.confidence >= 0.6).sort((a,b) => b.confidence - a.confidence).slice(0, 6).map((p, i) => {
                const confColor = p.confidence >= 0.7 ? "#22C55E" : T.accent;
                return (
                  <div key={i} style={{
                    ...cardStyle(false),
                    borderLeft: `3px solid ${confColor}`,
                    transition: "all 0.2s ease",
                  }}>
                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                      <span style={{ fontSize: 12, fontWeight: 700, color: T.textPrimary }}>{p.category}</span>
                      <span style={{ fontSize: 11, fontWeight: 700, color: confColor }}>{Math.round(p.confidence * 100)}%</span>
                    </div>
                    <div style={{ fontSize: 11, color: T.textSecondary, marginTop: 4 }}>[{p.system}] {p.prediction.slice(0, 80)}...</div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {activeTab === "Planets" && <PlanetTable data={data} />}
        {activeTab === "Dashas" && <DashaTimeline data={data} />}
        {activeTab === "KP System" && <KPSystemView data={data} />}
        {activeTab === "Predictions" && <PredictionsView data={data} />}
        {activeTab === "Ashtakavarga" && <AshtakavargaView data={data} />}
      </div>

      {/* Footer */}
      <div style={footerStyle}>
        <div style={{ fontSize: 10, color: T.textMuted }}>
          Silicon Siddhanta v1.0.0 | Swiss Ephemeris | Lahiri Ayanamsha {data.ayanamsha}°
        </div>
        <div style={{ fontSize: 9, color: T.border, marginTop: 4 }}>
          Parashari + KP (Krishnamurti Paddhati) + Nadi Systems | 3,103 lines of deterministic computation
        </div>
      </div>
    </div>
  );
}
